[package]
name = "nexrad-model"
version = "0.1.0-rc1"
description = "Common model for NEXRAD weather radar data."
authors = ["Daniel Way <contact@danieldway.com>"]
repository = "https://github.com/danielway/nexrad"
license = "MIT"
exclude = [".github"]
edition = "2021"

[dependencies]
chrono = { workspace = true, optional = true }
uom = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
